### ISSUE TITLE
Make compatible with Atramhasis 2.0.0

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis_scaffold_cookiecutter#10]
The current version was written for 1.3.x. Some updates for 2.0.0 are needed, especially in configuring the database. The demo providers should be in the database.

**Comment by Wim-De-Clercq** [comment]
Linking related atramhasis issue tracking the creation of database providers by initializing database. https://github.com/OnroerendErfgoed/atramhasis/issues/848

**Comment by goessebr** [comment]
The cookiecutter code was integrated in atramhasis since release 2.1.0: https://github.com/OnroerendErfgoed/atramhasis/releases/tag/2.1.0

Documentation can be found at:
- Create your own custom project: https://atramhasis.readthedocs.io/en/latest/customisation.html#creating-your-own-project
- Create a demo project: https://atramhasis.readthedocs.io/en/latest/demo.html#running-a-demo-site-with-cookiecutter
