### ISSUE TITLE
Remove with_ extension from development.ini

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis_scaffold_cookiecutter#8]
The current development.ini loads an extensions jinja2.ext.with_ that was removed in Jinja2 version 3. This leads to errors such as https://github.com/OnroerendErfgoed/atramhasis/issues/747 Easiest fix seems to be to remove the with_ extension from the development.ini

**Comment by goessebr** [comment]
The cookiecutter code was integrated in atramhasis since release 2.1.0: https://github.com/OnroerendErfgoed/atramhasis/releases/tag/2.1.0

Documentation can be found at:
- Create your own custom project: https://atramhasis.readthedocs.io/en/latest/customisation.html#creating-your-own-project
- Create a demo project: https://atramhasis.readthedocs.io/en/latest/demo.html#running-a-demo-site-with-cookiecutter
